"""Initial schema with all models

Revision ID: 165655e61514
Revises: 001
Create Date: 2026-01-01 23:01:02.184653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165655e61514'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sermons', sa.Column('formatted_transcript', sa.Text(), nullable=True))
    op.add_column('sermons', sa.Column('big_idea', sa.Text(), nullable=True))
    op.add_column('sermons', sa.Column('primary_scripture', sa.JSON(), nullable=True))
    op.add_column('sermons', sa.Column('topics', sa.JSON(), nullable=True))
    op.add_column('sermons', sa.Column('discussion_guide_json', sa.JSON(), nullable=True))
    op.add_column('sermons', sa.Column('ai_content_json', sa.JSON(), nullable=True))
    op.add_column('sermons', sa.Column('discussion_guide_url', sa.String(length=500), nullable=True))
    op.add_column('sermons', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.drop_column('sermons', 'discussion_guide')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sermons', sa.Column('discussion_guide', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sermons', 'processing_started_at')
    op.drop_column('sermons', 'discussion_guide_url')
    op.drop_column('sermons', 'ai_content_json')
    op.drop_column('sermons', 'discussion_guide_json')
    op.drop_column('sermons', 'topics')
    op.drop_column('sermons', 'primary_scripture')
    op.drop_column('sermons', 'big_idea')
    op.drop_column('sermons', 'formatted_transcript')
    # ### end Alembic commands ###
